### PR TITLE
Support :if and :unless for track_history callbacks

### PR DESCRIPTION
**Pull request by JagdeepSingh**
Raised for https://github.com/mongoid/mongoid-history/pull/209 with RSpecs here.

### CODE REVIEW

**Comment by johnnyshields** [comment]
@dblock I'd appreciate if you can take a moment to merge 212, 211, and 210 and ideally cut a release.

**Comment by dblock** [comment]
Done. And this looks great, rebase/merge along.

**Comment by johnnyshields** [comment]
@JagdeepSingh please handle

**Comment by JagdeepSingh** [comment]
This will be conflicted again after merging #211. Will rebase it then.

**Comment by JagdeepSingh** [comment]
Rebased to latest _master_. @dblock Please merge.

**Comment by johnnyshields** [comment]
@dblock thanks for all your help. Can I ask you to cut an official release?

**Comment by dblock** [comment]
I can try to get to it in the next day or so, otherwise you can cut one too :)

**Pull request merged**
