### PR TITLE
Solution for tracking has_and_belongs_to_many relations

### PR DESCRIPTION
**Pull request by mikwat**
Currently, `has_and_belongs_to_many` relations are not tracked consistently. For example:

Given the following models:
```
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::History::Trackable

  field :title
  field :body
  has_and_belongs_to_many :tags
  track_history on: %i[all], track_create: true, track_update: true
end

class Tag
  include Mongoid::Document

  field :title
  has_and_belongs_to_many :posts
end
```

Create with tags works as expected:
```
tag = Tag.create!
post = Post.create!(tags: [tag])
post.history_trackers.to_a
=> [#<Tracker _id: 5a579e2e017491024889a7b9, 
  created_at: 2018-01-11 17:26:06 UTC, 
  updated_at: 2018-01-11 17:26:06 UTC, 
  association_chain: [{"name"=>"Post", "id"=>BSON::ObjectId('5a579e2e017491024889a7b8')}], 
  modified: {"tag_ids"=>[BSON::ObjectId('5a579e2e017491024889a7b7')]}, 
  original: {}, 
  version: 1, 
  action: "create", 
  scope: "post", 
  modifier_id: nil>]
```

However, changes are not recorded:
```
tag = Tag.create!
tag2 = Tag.create!
post = Post.create!(tags: [tag])
post.tags << tag2
post.history_trackers.to_a
=> [#<Tracker _id: 5a579e2e017491024889a7b9, 
  created_at: 2018-01-11 17:26:06 UTC, 
  updated_at: 2018-01-11 17:26:06 UTC, 
  association_chain: [{"name"=>"Post", "id"=>BSON::ObjectId('5a579e2e017491024889a7b8')}], 
  modified: {"tag_ids"=>[BSON::ObjectId('5a579e2e017491024889a7b7')]}, 
  original: {}, 
  version: 1, 
  action: "create", 
  scope: "post", 
  modifier_id: nil>]
```

Unfortunately, none of the document callbacks (i.e. `around_update`, `around_create`, `around_destroy`) are called when modifications are made to a `has_and_belongs_to_many` relation. From my reading of the [Mongoid docs](https://docs.mongodb.com/mongoid/master/tutorials/mongoid-callbacks/#relation-callbacks) and code, the only way to be notified of changes to these relations is to attach a callback directly to the relation definition.

While inconvenient, this proposed solution simply makes a callback method available that must be attached to each `has_and_belongs_to_many` relation via `before_add: :track_has_and_belongs_to_many, before_remove: :track_has_and_belongs_to_many`. I don't know of a way to automatically attach these callbacks, but please educate me if this is possible.

Here's an example of this solution in use:
```
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::History::Trackable

  field :title
  field :body
  has_and_belongs_to_many :tags, before_add: :track_has_and_belongs_to_many, before_remove: :track_has_and_belongs_to_many
  track_history on: %i[all], track_create: true, track_update: true
end

class Tag
  include Mongoid::Document

  field :title
  has_and_belongs_to_many :posts
end
```

```
tag = Tag.create!
tag2 = Tag.create!
post = Post.create!(tags: [tag])
post.tags << tag2
post.history_trackers.to_a
=> [
  #<Tracker _id: 5a57aa610174912e0c3edf88, 
    created_at: 2018-01-11 18:18:09 UTC, 
    updated_at: 2018-01-11 18:18:09 UTC, 
    association_chain: [{"name"=>"Post", "id"=>BSON::ObjectId('5a57aa610174912e0c3edf87')}], 
    modified: {"tag_ids"=>[BSON::ObjectId('5a57aa610174912e0c3edf85')]}, 
    original: {}, 
    version: 1, 
    action: "create", 
    scope: "post", 
    modifier_id: nil>, 
  #<Tracker _id: 5a57aa610174912e0c3edf89, 
    created_at: 2018-01-11 18:18:09 UTC, 
    updated_at: 2018-01-11 18:18:09 UTC, 
    association_chain: [{"name"=>"Post", "id"=>BSON::ObjectId('5a57aa610174912e0c3edf87')}], 
    modified: {"tag_ids"=>[BSON::ObjectId('5a57aa610174912e0c3edf85'), BSON::ObjectId('5a57aa610174912e0c3edf86')]}, 
    original: {"tag_ids"=>[BSON::ObjectId('5a57aa610174912e0c3edf85')]}, 
    version: 2, 
    action: "update", 
    scope: "post", 
    modifier_id: nil>
]
```

### CODE REVIEW

**Comment by mikwat** [comment]
Is the expected behavior, @dblock ? Basically, it appears that updates to `has_and_belongs_to_many` relations aren't tracked.

**Comment by dblock** [comment]
I would expect everything to be tracked, so we should call this a bug. Feel free to try a fix!

**Comment by mikwat** [comment]
@dblock When you have a chance, let me know your thoughts.

**Comment by dblock** [comment]
I think we should be able to attach those callbacks by examining all HABTM relationships in late binding, similarly to how we do for fields. This would avoid the whole explicit options to the relationship, wouldn't it?

**Comment by mikwat** [comment]
That would be great, but I'm not sure it's possible. `reflect_on_all_associations(:has_and_belongs_to_many)` returns an array of [Mongoid::Relations::Metadata](https://docs.mongodb.com/mongoid/master/tutorials/mongoid-relations/#metadata) instances, but how would you use these to add the necessary callbacks on the relation?

**Comment by dblock** [comment]
Maybe @estolfo can help with some pointers, please?

**Comment by dblock** [comment]
@mikwat Unrelated, but to just keep the parent repo clean maybe work off a fork? My OCD is kicking in :)

**Comment by mikwat** [comment]
Of course @dblock Sorry about that.

**Comment by mikwat** [comment]
Moved to https://github.com/mongoid/mongoid-history/pull/215

**Pull request closed without merging**
