### PR TITLE
Store options in inheritable class attributes.

### PR DESCRIPTION
**Pull request by jnfeinstein**
This fixes issue #226.  Underlying cause is that the options were
being keyed on collection name, which is able to be changed.
This change stores the options on the class itself where it will
always be available regardless of collection name.

### CODE REVIEW

**Comment by jnfeinstein** [comment]
@dblock this fixes #226.  Somehow all the tests pass.  Wicked!

**Comment by jnfeinstein** [comment]
Rubocop is throwing two errors on lines I didn't change.  Not sure what to do with those.

**Comment by dblock** [comment]
For rubocop run `rubocop -a ; rubocop --auto-gen-config`.

**Comment by dblock** [comment]
This is straightforward, I love it. It's a great incremental step on top of https://github.com/mongoid/mongoid-history/pull/208, I should have totally done that.

**Comment by dblock** [comment]
Optional/next steps: do we need `trackable_classes` at all at this point? We can iterate over mongoid models looking for any that implement trackable history to reimplement `reset!`, which I think is only used for tests anyway.

Make sure to update CHANGELOG and fix rubocop and it's good to go!

**Comment by jnfeinstein** [comment]
@dblock this PR has been updated per your suggestions.

I added a commit that allows Travis to use the latest prebuilt ruby in the 2.3 tree.  This knocks off ~18s per build.  I can open a separate PR for this if that's preferred.

**Comment by dblock** [comment]
@jnfeinstein Merged, much thanks. You seem to know what you're doing :) Want to help out with the maintenance of mongoid-history? If yes you can make the next release and I'll gladly add you to rubygems (what's your email?).

**Comment by jnfeinstein** [comment]
Thanks.  I'm happy to help out when I can.

**Comment by dblock** [comment]
Thanks! Care to email me your rubygems.org email?

**Pull request merged**
